name: 🔗 GHA - Build Engine
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Windows - Editor
    uses: ./.github/workflows/editor.yml